# Generated by Django 5.1.7 on 2025-05-17 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='blog.categories'),
            preserve_default=False,
        ),
    ]
