# Generated by Django 5.1.7 on 2025-05-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_category_categories_article_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='categorie',
        ),
    ]
