# Generated by Django 5.1.7 on 2025-05-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorie',
            new_name='Category',
        ),
    ]
