# Generated by Django 5.1.7 on 2025-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_categorie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=600)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
